var obj= {
	"categories":["What to do tonight? ", "Select a category", "Movies", "Games", "Nap time..."],
	"Movies":["Movies!! Of course! ", "Select a genre","Action", "Adventure", "Drama", "SciFi", "Horror"],
	
	"Action":["Sounds exciting! ", "Select a subgenre", "Thriller","Car racing","Superhero"],
	"Thriller":["Dun Dun Dun! ", "Which actor you wanna see? ", "Hugh Jackman", "Leonardo DiCaprio", "Jodie Foster"],
	
	"Leonardo DiCaprio":["Leo D.", "Select a movie", "Inception", "Shutter Island", "Great Gatsby"],
	"Inception":[" ", "incept.jpg"],
	"Shutter Island":[" ", "shutter.jpg"],
	"Great Gatsby":[" ", "gatsby.jpeg"],
	
	"Jodie Foster":["Jodie F.", "Select a movie", "The Silence of the Lamb", "Flight Plan", "Elysium"],
	"The Silence of the Lamb":[" ", "silence.jpg"],
	"Flight Plan":[" ", "flight.jpg"],
	"Elysium":[" ", "elys.jpg"],
	
	"Hugh Jackman":["Hugh J.", "Select a movie", "Wolverine", "Les Mis"],
	"Wolverine":[" ", "wolf.jpg"],
	"Les Mis":[" ", "les.jpg"],
	
	"Car racing":["VREOWW ", "Select a movie", "Fast and Furious", "Herbie", "Dust to Glory"],
	"Fast and Furious":[" ", "fast.jpg"], 
	"Herbie":[" ", "herbie.jpg"], 
	"Dust to Glory":[" ", "dust.jpg"],
	
	
	"Superhero":["'Why so serious?' ", "Select a movie", "Iron Man", "Man of Steel"],
	"Iron Man":[" ", "iron.jpg"], 
	"Man of Steel":[" ", "super.jpg"],
	
	"Adventure":["Up, up, and away!", "Select a subgenre", 'Fantasy','Family film','Disasters'],
	"Fantasy":["I summon my purple unicorn! ", "Select a movie", "Lord of the Rings", "Harry Potter"],
	"Lord of the Rings":[" ", "lotr.jpg"],
	"Harry Potter":[" ", "harry.jpg"],
	
	"Family film":["Friendly features", "Select a movie", "Bambi", "Despicable Me", "The Incredibles"],
	"Bambi":[" ", "bambi.jpg"], 
	"Despicable Me":[" ", "despic.jpg"],
	"The Incredibles":[" ", "incredibles.jpg"],
	
	
	"Disasters":["Your choice of impending doom: ", "Select one", "Volcanoes", "Tsunami", "EarthQuakes"],
	"Volcanoes":[" ", "volcano.jpg"],
	"Tsunami":[" ", "tsunami.jpg"],
	"EarthQuakes":[" ", "earthquake.jpg"],
	
	"Drama":["Grab some popcorn...", "Select a subgenre", "Murders","Foreign drama","Love Story"],
	"Murders":["Not my cup of tea...", "Select a movie", "CSI", "Criminal Minds", "Sherlock Holmes"],
	"CSI":[" ", "csi.jpg"], 
	"Criminal Minds":[" ", "crime.jpg"], 
	"Sherlock Holmes":[" ", "holmes.jpg"],
	
	"Foreign drama":["Qu'est que ce?", "Select a movie", "Mountain Patrol", "Kandahar", "Life of Pi"],
	"Mountain Patrol":[" ", "mountain.jpg"], 
	"Kandahar":[" ", "kandar.jpg"], 
	"Life of Pi":[" ", "pi.jpg"],
	
	"Love Story":["*Swoon*", "Select a movie", "Piano Teacher", "Dear John", "Titanic"],
	"Piano Teacher":[" ", "piano.jpg"], 
	"Dear John":[" ", "john.jpg"], 
	"Titanic":[" ", "titanic.jpg"],
	
	"SciFi":["Doo do oo oo ", "Select a subgenre", "Otherworldly","Cartoons","Post Apocalypse"],
	"Otherworldly":["Beam me up", "Select a movie", "Aliens", "Avatar", "E.T"],
	"Aliens":[" ", "aliens.jpg"],
	"Avatar":[" ", "avatar.jpg"],	
	"E.T":[" ", "ET.jpg"],
	
	
	"Cartoons":["Round and round they go", "Select a movie", "Futurama", "American Dad", "Family Guy"],
	"Futurama":[" ", "future.jpg"], 
	"American Dad":[" ", "american.jpg"], 
	"Family Guy":[" ", "family.png"],
	
	"Post Apocalypse":["It's up to you to save the world ", "Select a movie", "Dawn of Dead", "Rise of Dead", "World War Z"],
	"Dawn of Dead":[" ", "dawn.jpg"], 
	"Rise of Dead":[" ", "rise.jpg"],
	"World War Z":[" ", "wwz.jpg"],
	
	"Horror":["Ooh SCARY!!", "Select a subgenre", "Monsters","Evil Children","Stalkers"],
	"Monsters":["Shhh... behind you!", "Select a movie", "Anaconda", "Jurassic Park", "Coraline"],
	"Anaconda":[" ", "anaconda.jpg"], 
	"Jurassic Park":[" ", "jura.jpg"],
	"Coraline":[" ", "coral.jpg"],
	
	"Evil Children":["heee he eheeE ", "Select a movie", "Chucky", "ParaNorman"],
	"Chucky":[" ", "chuck.jpg"],
	"ParaNorman":[" ", "para.jpg"],
	
	"Stalkers":["I'm gonna get you! ", "Select a movie", "American Psycho"],
	"American Psycho":[" ", "psycho.jpg"],
	
	
	"Games":["Which console do you want to play? ", "Select a console", "Gameboy", "Wii", "XBOX", "Computer"],
	"Gameboy":["Which model? ", "Select a model", "Advanced", "3DS"],
	"Advanced":[" ", "oops.png"],
	
	"3DS":["Select a game", "Which game?", "Mario", "Pokemon"],
	"Mario":[" ", "mario.jpg"],
	"Pokemon":[" ", "poke.jpg"],
	
	"Wii":["Select a game", "Which game?", "Legend of Zelda", "Super Smash Bros"],
	"Legend of Zelda":[" ", "zelda.jpg"], 
	"Super Smash Bros":[" ", "smash.jpg"],
	
	"XBOX":["Select a game", "Which game?", "MineCraft", "Grand Theft Auto"],
	"MineCraft":[" ", "minec.jpg"],
	"Grand Theft Auto":[" ", "grand.jpg"],
	
	"Computer":["Select a genre", "Which genre? ", "MMO", "RTS", "Puzzle"],
	"MMO":["Select a game", "...", "WoW", "Guild Wars"],
	"WoW":[" ", "wow.jpg"],
	"Guild Wars":[" ", "gw2.jpg"],
	
	"RTS":["Select a game", "...", "League of Legends", "DoTa"],
	"League of Legends":[" ", "league.jpg"],
	"DoTa":[" ", "dota.jpg"],
	
	"Puzzle":["Select a game", "...", "Mahjong", "Solitaire", "Puzzle Pirates"],
	"Mahjong":[" ", "mahjong.gif"],
	"Puzzle Pirates":[" ", "puzzle.jpg"],
	"Solitaire":[" ", "solitaire.jpg"],
	
	"Nap time...":[" ", "zZz.gif"]
	}